import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/Navbar";
import { SpeedInsights } from '@vercel/speed-insights/next';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning={true} lang="en">
      <AuthProvider>
      <body className={inter.className}>
        <Navbar />
        {children}
      <Toaster />
      <SpeedInsights />
      </body>
      </AuthProvider>
      
    </html>
  );
}
